# Gradient Boosting Regressor
# @package model

name: gradient_boosting

# Параметры бустинга
n_estimators: 100        # Количество этапов (10-1000)
learning_rate: 0.1       # Скорость обучения (0-1)
max_depth: 3             # Глубина деревьев (1-50)

# Параметры разбиения
min_samples_split: 2     # Минимум образцов для разбиения
min_samples_leaf: 1      # Минимум образцов в листе

# Стохастичность
subsample: 1.0           # Доля образцов для каждого дерева (0-1)

# Функция потерь
loss: squared_error      # squared_error, absolute_error, huber, quantile

# Воспроизводимость
random_state: 42
